### ISSUE TITLE
Sometimes, RSCP Frame Answer parsing failes

### ISSUE THREAD

**Issue by jnk-cons** [jnk-cons/easy-rscp-js#16]
The reason is currently unknown. However, when reading the BAtterie monitoring data, a parsing error sometimes occurs when reading the data block length.

In any case, the error handling in the services must be adapted so that it does not lead to a crash, but to a call to reject().

Further analysis will follow:

```
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 389. Received 391
    at new NodeError (node:internal/errors:387:5)
    at boundsError (node:internal/buffer:86:9)
    at Buffer.readUInt16LE (node:internal/buffer:243:5)
    at DefaultDataParser.readLength (/app/node_modules/easy-rscp/dist/lowlevel/frame/default-data-parser.js:37:22)
    at DefaultDataParser.parseSingleData (/app/node_modules/easy-rscp/dist/lowlevel/frame/default-data-parser.js:21:29)
    at DefaultDataParser.parseRSCPData (/app/node_modules/easy-rscp/dist/lowlevel/frame/default-data-parser.js:12:35)
    at Data.valueAsContainer (/app/node_modules/easy-rscp/dist/api/frame/data.js:99:27)
    at Frame.find (/app/node_modules/easy-rscp/dist/api/frame/frame.js:49:45)
    at Frame.numberByTag (/app/node_modules/easy-rscp/dist/api/frame/frame.js:57:28)
    at /app/node_modules/easy-rscp/dist/service/default-battery-service.js:73:50 {
`

**Comment by jnk-cons** [comment]
Improvement of error handling is implemented in 0.8.1. Error must be monitored further, as it cannot be reproduced outside the Homey runtime environment
